export const BOOK_LIST = [
	{
		id: 'book_0001',
		name: 'The Old Man and the Sea',
		author: 'Ernest Hemingway',
		description:
			'A powerful story of struggle and endurance, Hemingway’s classic novella follows an aging fisherman’s battle with a giant marlin in the Gulf Stream',
		price: 6.74,
	},
	{
		id: 'book_0002',
		name: 'The Star Rover',
		author: 'Jack London',
		description:
			'A gripping tale of adventure and self-discovery, this novel follows a man who experiences his past lives through intense astral projection, blending themes of freedom, rebellion, and the human spirit',
		price: 5.89,
	},
	{
		id: 'book_0003',
		name: 'I, Robot',
		author: 'Isaac Asimov',
		description:
			'A collection of interconnected stories that explore the ethical dilemmas and complexities of artificial intelligence, set in a future shaped by robotics and science fiction',
		price: 5.27,
	},
	{
		id: 'book_0004',
		name: 'All Quiet on the Western Front',
		author: 'Erich Maria Remarque',
		description:
			'A poignant and harrowing account of a young German soldier’s experiences in World War I, capturing the brutal realities of war and the disillusionment it brings',
		price: 8.99,
	},
];
