import the_old_man_and_the_sea_ernest_hemingway from '../../assets/books_covers/the_old_man_and_the_sea_ernest_hemingway.jpg';
import the_star_rover_jack_london from '../../assets/books_covers/the_star_rover_jack_london.jpg';
import i_robot_isaac_asimov from '../../assets/books_covers/i_robot_isaac_asimov.jpg';
import all_quiet_on_the_western_front_erich_maria_remarque from '../../assets/books_covers/all_quiet_on_the_western_front_erich_maria_remarque.jpg';

export const BOOK_LIST = [
	{
		id: 'book_0001',
		name: 'The Old Man and the Sea',
		author: 'Ernest Hemingway',
		description:
			'A powerful story of struggle and endurance, Hemingway’s classic novella follows an aging fisherman’s battle with a giant marlin in the Gulf Stream',
		price: 6.74,
		cover: the_old_man_and_the_sea_ernest_hemingway,
	},
	{
		id: 'book_0002',
		name: 'The Star Rover',
		author: 'Jack London',
		description:
			'A gripping tale of adventure and self-discovery, this novel follows a man who experiences his past lives through intense astral projection, blending themes of freedom, rebellion, and the human spirit',
		price: 5.89,
		cover: the_star_rover_jack_london,
	},
	{
		id: 'book_0003',
		name: 'I, Robot',
		author: 'Isaac Asimov',
		description:
			'A collection of interconnected stories that explore the ethical dilemmas and complexities of artificial intelligence, set in a future shaped by robotics and science fiction',
		price: 5.27,
		cover: i_robot_isaac_asimov,
	},
	{
		id: 'book_0004',
		name: 'All Quiet on the Western Front',
		author: 'Erich Maria Remarque',
		description:
			'A poignant and harrowing account of a young German soldier’s experiences in World War I, capturing the brutal realities of war and the disillusionment it brings',
		price: 8.99,
		cover: all_quiet_on_the_western_front_erich_maria_remarque,
	},
];
